server:
  port: 8022
spring:
  #是否启用延时队列
  delay: true
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
    host: 192.168.159.128
    port: 5672
    username: guest
    password: guest
