server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.25.11.67
    port: 5672
    username: root
    password: 123456
    publisher-confirm-type: correlated
    publisher-returns: true   # 开启返回模式
    template:
      mandatory: true         # 必须设置为true，否则ReturnCallback不生效
